# Generated by Django 6.0.6 on 2026-06-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Administrator', 'Administrator'), ('Teacher', 'Teacher'), ('Learner', 'Learner')], max_length=20),
        ),
    ]
